---
- name: Create download directory
  file:
    dest: "{{ maven_download_dir }}"
    state: directory
    mode: "0755"

- name: Download Maven package
  get_url:
    url: "{{ maven_mirror }}/{{ maven_redis_filename }}"
    dest: "{{ maven_download_dir }}/{{ maven_redis_filename }}"
  retries: 3
  delay: 2
  register: result
  until: result is succeeded

- name: Install unarchive module dependencies
  package:
    name:
      - tar
      - unzip
      - gzip
    state: present
  become: true

- name: Create Maven installation directory
  file:
    path: "{{ maven_install_dir }}"
    state: directory
    mode: "0755"
  become: true

- name: Unpack Maven package
  unarchive:
    src: "{{ maven_download_dir }}/{{ maven_redis_filename }}"
    dest: "{{ maven_install_dir }}"
    remote_src: true
    creates: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}"
  become: yes

- name: Copy Maven profile file
  template:
    src: maven.sh.j2
    dest: /etc/profile.d/maven.sh
  become: true
  when: maven_is_default_installation | bool
