---
- name: Download Maven package
  get_url:
    url: "{{ maven_download_url }}"
    dest: "/tmp/{{ maven_file_name }}"
  retries: 3
  delay: 2
  register: result
  until: result is succeeded
  delegate_to: localhost
  become: false

- name: Create Maven installation directory if it does not exist
  file:
    path: "{{ maven_install_dir }}"
    state: directory
    mode: "0755"
  become: true

- name: Unpack Maven package
  unarchive:
    src: "/tmp/{{ maven_file_name }}"
    dest: "{{ maven_install_dir }}"
    creates: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}"
  become: yes

- name: Configure Maven settings
  template:
    src: maven.sh.j2
    dest: /etc/profile.d/maven.sh
  become: true
  when: maven_is_default_installation
