---
- name: Check Maven version is present
  shell: "mvn -v | grep 'Apache Maven {{ maven_version }}'"
  register: maven_version_check
  failed_when: no
  changed_when: no

- debug: msg="{{ maven_version_check }}"

- name: Install Maven
  include_tasks: install.yml
  when: maven_version_check.rc != 0
